const fs = require('fs');
const path = require('path');

// Load the generated TypeScript file as a module
// Since it's an ES module, we can use import() if we are in an ES module context.
// However, to keep it simple and compatible with CommonJS, we'll rename the file to .js and remove the export line?
// Alternatively, we can use dynamic import in an async function.

// Let's read the file and extract the object by removing the export line and wrapping in a function.
// But note: the file has comments at the top.

// We'll do:
//   const fileContent = fs.readFileSync(path.resolve(__dirname, '../app/data/assistArticulations.ts'), 'utf8');
//   // Remove the first two lines (comments) and the export line.
//   const jsonStr = fileContent.split('\n').slice(3).join('\n'); // Remove first 3 lines: two comments and the export line?
//   Actually, the export line is: export const assistRequirements = {
//   We want to remove the 'export const assistRequirements = ' part and the trailing semicolon? There is none.

// Let's try a different approach: use the Node.js module system by temporarily renaming the file to .js and requiring it.
// But we don't want to alter the original.

// Instead, let's use the fact that the file is valid JSON if we remove the export line and the comments.
// We'll create a temporary string that is the object.

const filePath = path.resolve(__dirname, '../app/data/assistArticulations.ts');
let fileContent = fs.readFileSync(filePath, 'utf8');

// Remove the first two lines (comments)
fileContent = fileContent.split('\n').slice(2).join('\n');
// Now the first line is: export const assistRequirements = {
// We want to remove 'export const assistRequirements = ' from the beginning and the semicolon at the end? There is no semicolon.
const exportRegex = /^export\s+const\s+assistRequirements\s+=\s+/;
fileContent = fileContent.replace(exportRegex, '');

// Now fileContent should be the object starting with { and ending with }.
// We'll wrap it in a function to parse it safely? Instead, we can use `eval` but that's dangerous.
// Since we trust the file, we can use Function constructor.

// Alternatively, we can just write the object as is to a JSON file and then parse it? But we need to ensure it's valid JSON.
// The TypeScript object may have trailing commas? No, it's generated by a script that should produce valid JS object.

// Let's try to evaluate it in a safe way by using vm module? But for simplicity, we'll assume it's valid JSON if we remove the export line.

// Actually, the generated file is valid JavaScript object. We can assign it to a variable by wrapping in parentheses and then using Function.

const wrapped = `(function () { return ${fileContent} })()`;
let assistRequirements;
try {
  assistRequirements = eval(wrapped);
} catch (e) {
  console.error('Failed to parse assistRequirements from TS file:', e);
  process.exit(1);
}

// Now generate assistOptions from assistRequirements using the same logic as in PlannerClient
function buildRequirementOptions(database) {
  const colleges = Object.keys(database).sort((a, b) => a.localeCompare(b));
  const targetsByCollege = {};
  const majorsByCollegeAndTarget = {};

  for (const college of colleges) {
    const targets = Object.keys(database[college] ?? {}).sort((a, b) =>
      a.localeCompare(b)
    );
    targetsByCollege[college] = targets;
    majorsByCollegeAndTarget[college] = {};

    for (const target of targets) {
      majorsByCollegeAndTarget[college][target] = Object.keys(
        database[college]?.[target] ?? {}
      ).sort((a, b) => a.localeCompare(b));
    }
  }

  return { colleges, targetsByCollege, majorsByCollegeAndTarget };
}

const assistOptions = buildRequirementOptions(assistRequirements);

// Prepare the final object to write
const output = {
  assistRequirements,
  assistOptions
};

// Write to public/data/assist_articulations.json
const outputPath = path.resolve(__dirname, '../public/data/assist_articulations.json');
fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));
console.log(`Generated ${outputPath}`);